name:                solitaire
version:             0.1.0.0
github:              "CharlesTaylor7/solitaire"
license:             BSD3
author:              "Charles Taylor"
maintainer:          "charlestaylor95@gmail.com"
copyright:           "2019 Charles Taylor"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CharlesTaylor7/solitaire#readme>

dependencies:
- base >= 4.7 && < 5
- rio
- containers
- vector
- mtl
- lens
- MonadRandom
- pipes

default-extensions:
  - NoImplicitPrelude
  - AllowAmbiguousTypes
  - TypeApplications
  - GeneralizedNewtypeDeriving
  - DeriveGeneric
  - DerivingStrategies
  - MultiParamTypeClasses
  - PartialTypeSignatures
  - MonoLocalBinds
  - TupleSections
  - ScopedTypeVariables
  - RankNTypes
  - OverloadedLists
  - OverloadedStrings
  - GADTs
  - LambdaCase
  - FlexibleContexts
  - ConstraintKinds

ghc-options:
  - -Wno-deprecations

library:
  source-dirs: src

executables:
  solitaire-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solitaire

tests:
  solitaire-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solitaire
    - hspec
    - QuickCheck
