name:                solitaire
version:             0.1.0.0
github:              "CharlesTaylor7/solitaire-hs"
license:             BSD3
author:              "Charles Taylor"
maintainer:          "charlestaylor95@gmail.com"
copyright:           "2019 Charles Taylor"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CharlesTaylor7/solitaire-hs#readme>

dependencies:
- base >= 4.7 && < 5
 # data types
- text
- bytestring
- containers
- unordered-containers
- hashable >= 1.3
- vector
# priority queues
- pqueue
# difference lists
- dlist >= 1.0
# higher order open sum types
- fastsum
# control flow
- lens
- generic-lens
- mtl
- transformers
- MonadRandom
# color terminal output
- rainbow

default-extensions:
  # always
  - NoImplicitPrelude
  - ScopedTypeVariables
  - PartialTypeSignatures
  - MonoLocalBinds
  - InstanceSigs

  # type applications
  - AllowAmbiguousTypes
  - TypeApplications

  # deriving extensions
  - GeneralizedNewtypeDeriving
  - DeriveGeneric
  - DerivingStrategies
  - StandaloneDeriving
  - DerivingVia
  - DeriveAnyClass

  # sugar
  - TupleSections
  - LambdaCase

  # required to work with libs
  - RankNTypes
  - FlexibleContexts
  - ConstraintKinds

  # overloaded
  - OverloadedLists
  - OverloadedStrings
  - OverloadedLabels

  # generic lens
  - DuplicateRecordFields

  # because what could go wrong
  - TypeFamilies
  - TypeFamilyDependencies
  - GADTs

  # mtl style typeclasses
  - FunctionalDependencies
  - MultiParamTypeClasses

ghc-options:
  - -Wall
  - -Werror
  - -Wno-name-shadowing
  - -Wno-unused-imports
  - -Wno-unused-local-binds
  - -Wno-unused-matches
  - -freverse-errors

library:
  source-dirs: src

executables:
  solitaire-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solitaire

tests:
  solitaire-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - solitaire
    - hspec
    - QuickCheck
